def update(input_file_path, output_file_path, variable_name):
    with open(input_file_path, 'rb') as f:
        bts = f.read()
    with open(output_file_path, 'w') as o:
        o.write("// this file is auomatically generated by update_resources.py\n")
        o.write(f"const unsigned char {variable_name} [{len(bts)}] = ")
        o.write("{\n    ")

        o.write(','.join([str(x) for x in bts]))

        o.write("\n};")

update("UnityUI\\Assets\\AssetBundlesAndroid\\defaultwidget", "src\\DefaultUI.inl", "default_ui")
update("extra/HeartBeatBLEReader.dex", "src\\HeartBeatBLEDex.inl", "ble_dex")