INPUT = "UnityUI\\Assets\\AssetBundles\\defaultwidget"

OUTPUT = "src\\DefaultUI.inl"

with open(INPUT, 'rb') as f:
    bts = f.read()
with open(OUTPUT, 'w') as o:
    o.write("// this file is auomatically generated by update_default_ui.py\n")
    o.write(f"const unsigned char default_ui [{len(bts)}] = ")
    o.write("{")

    o.write(','.join([str(x) for x in bts]))

    o.write("};")
