#ifndef V
#define V(key, value)
#endif
V(enabled, "启用(重启生效)")
V(hyperate, "HypeRate")

V(hyperate_reset, "重置")
V(hyperate_save_and_connect, "保存并连接")
V(hyperate_input_hint, "https://app.hyperate.io/<color=\"green\">xxx</color><-输入这个")

V(no_message_from_server, "")

V(lang_name, "chinese")

V(unsupported_feature_udpatre_mod, "UI不支持,可能需要升级MOD")

V(heart_config, "心率设置")
V(heart_devices, "心率设备")
V(heart_senders, "心率数据源")
V(heart_osc_senders, "OSC心率源")

V(heart_osc_port, "OSC端口号: %d")

V(pairing, "正在配对，点击停止")
V(not_pairing, "配对停止，点击开始")
V(hiding_mac_addr, "MAC地址已隐藏，点击显示")
V(showing_mac_addr, "MAC地址已显示，点击隐藏")
V(unknown_left_quote, "未知(")
V(server_skip, "已跳过 ")
V(unknown_addr_server_fmt, "%s 未知地址。")
V(heart_rate_lan_protocol_ver, "Heart Rate Lan 协议版本：")
V(mod_version, "模组版本 " VERSION)
V(for_game, "适配游戏版本" GAME_VERSION)
V(no_beatleader, "Beatleader未找到或不支持，录制已禁用")
V(waiting, "等待中...")

V(text_color, "文字颜色")
V(flash_text_color, "闪烁颜色")
V(replay_flash_text_color, "录像闪烁颜色")
V(flash_duration_when_text_come, "数据抵达时的闪烁时长")
V(flash_test, "闪烁测试")
V(reset_to_default, "恢复默认")

V(scan_devices,"扫描设备")
V(data_source, "数据源(重启生效)")

//BUG: can't translate text inside dropdown
//V(data_source_random, "随机")
//V(data_source_lan, "局域网")
//V(data_source_bluetooth, "蓝牙")

V(enable_record, "启用录像")
V(record_dev_name, "保存设备名到录像")

V(age, "年龄")

V(select_ui, "界面选择")
V(max_heart, "最大心率")