#ifndef V
#define V(key, value)
#endif
V(enabled, "启用(设置后重启)")

V(heart_config, "心率设置")
V(heart_devices, "心率设备")
V(heart_senders, "心率数据源")

V(pairing, "正在配对，点击停止")
V(not_pairing, "配对停止，点击开始")
V(hiding_mac_addr, "MAC地址已隐藏，点击显示")
V(showing_mac_addr, "MAC地址已显示，点击隐藏")
V(unknown_left_quote, "未知(")
V(server_skip, "已跳过 ")
V(unknown_addr_server_fmt, "%s 未知地址。")
V(heart_rate_lan_protocol_ver, "Heart Rate Lan 协议版本：")
V(mod_version, "模组版本 " VERSION)
V(waiting, "等待中...")

V(text_color, "文字颜色")
V(flash_text_color, "闪烁颜色")
V(flash_duration_when_text_come, "数据抵达时的闪烁时长")
V(flash_test, "闪烁测试")
V(reset_to_default, "恢复默认")

V(scan_devices,"扫描设备")
