#ifndef V
#define V(key, value)
#endif
V(enabled, "enabled(need restart)")

V(heart_config, "HEART Config")
V(heart_devices, "HEART Devices")
V(heart_senders, "HEART Senders")

V(pairing, "Pairing.. click to stop.")
V(not_pairing, "Not pairing.. click to start.")
V(hiding_mac_addr, "hiding mac address, click to show.")
V(showing_mac_addr, "showing mac address, click to hide")
V(unknown_left_quote, "Unknown(")
V(server_skip, "skip ")
V(unknown_addr_server_fmt, "%s unknown addr.")
V(heart_rate_lan_protocol_ver, "Heart Rate Lan Protocol Ver ")
V(mod_version, "Mod version " VERSION)
V(waiting, "Waiting...")

V(config_adjust_speed, "Config Adjust Speed")

V(text_color, "Text Color")
V(flash_text_color, "Flash Text Color")
V(flash_duration_when_text_come, "Flash duration when data come")
V(flash_test, "Flash Test")

V(line_space, "Line Space")
V(reset_default_line_space, "Reset Default Line Space")

V(reset_to_default, "Reset to default")

V(scan_devices,"scan devices")
V(data_source, "data source(need restart)")

V(data_source_random, "random")
V(data_source_lan, "lan")
V(data_source_bluetooth, "bluetooth")