#ifndef V
#define V(key, value)
#endif
V(enabled, "enabled(need restart)")

V(lang_name, "english")

V(heart_config, "HEART Config")
V(heart_devices, "HEART Devices")
V(heart_senders, "HEART Senders")
V(heart_osc_senders, "HEART OSC Senders")
V(hyperate, "HypeRate")

V(hyperate_reset, "RESET")
V(hyperate_save_and_connect, "SAVE AND CONNECT")
V(hyperate_input_hint, "https://app.hyperate.io/<color=\"green\">xxx</color><-input this")
V(no_message_from_server, "")

V(unsupported_feature_udpatre_mod, "UI unsupported, maybe update your mod")

V(heart_osc_port, "OSC Port: %d")

V(pairing, "Pairing.. click to stop.")
V(not_pairing, "Not pairing.. click to start.")
V(hiding_mac_addr, "hiding mac address, click to show.")
V(showing_mac_addr, "showing mac address, click to hide")
V(unknown_left_quote, "Unknown(")
V(server_skip, "skip ")
V(unknown_addr_server_fmt, "%s unknown addr.")
V(heart_rate_lan_protocol_ver, "Heart Rate Lan Protocol Ver ")
V(mod_version, "Mod version " VERSION)
V(for_game, "For Game " GAME_VERSION)
V(waiting, "Waiting...")

V(config_adjust_speed, "Config Adjust Speed")

V(text_color, "Text Color")
V(flash_text_color, "Flash Text Color")
V(replay_flash_text_color, "Replay Flash Text Color")
V(flash_duration_when_text_come, "Flash duration when data come")
V(flash_test, "Flash Test")

V(line_space, "Line Space")
V(reset_default_line_space, "Reset Default Line Space")

V(reset_to_default, "Reset to default")

V(scan_devices,"scan devices")
V(data_source, "data source(need restart)")

V(data_source_random, "random")
V(data_source_lan, "(deprecated)local network")
V(data_source_bluetooth, "bluetooth")
V(data_source_osc, "OSC")
V(data_source_hyperate, "HypeRate")


V(enable_record, "Enable Record")
V(record_dev_name, "Save Device Name To Record")

V(age, "Age")

V(select_ui, "Select UI")
V(max_heart, "Max Heartrate")