name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup qpm
      run: wget https://github.com/QuestPackageManager/QPM.CLI/releases/download/v1.3.1/qpm-windows-x64.zip
    - name: unzip qpm
      run: \"C:\\Program Files\\7-Zip\\7z.exe\" e qpm-windows-x64.zip
  
    - name: echo everything
      run: dir
