name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup qpm
      run: Invoke-WebRequest https://github.com/QuestPackageManager/QPM.CLI/releases/download/v1.3.1/qpm-windows-x64.zip -OutFile qpm-windows-x64.zip 
    - name: unzip qpm
      run:  7z e qpm-windows-x64.zip
    - name: setup ndk
      run: echo %ANDROID_NDK% > ndkpath.txt
    - name: setup system path
      run: echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
    - name: qpm.exe restore
      run: qpm.exe restore
    - name: build
      run: qpm.exe s build
    - name: make qmod
      run: .\scripts\createqmod.ps1
    - name: echo everything
      run: dir
    - uses: actions/upload-artifact@v4
      with:
        name: HeartBeatQuest.qmod
        path: HeartBeatQuest.qmod
        overwrite: true
