name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup qpm
      run: Invoke-WebRequest https://github.com/QuestPackageManager/QPM.CLI/releases/download/v1.3.1/qpm-windows-x64.zip -OutFile qpm-windows-x64.zip 
    - name: unzip qpm
      run:  7z e qpm-windows-x64.zip
    - name: setup ninja
      run: Invoke-WebRequest https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip -OutFile ninja-win.zip 
    - name: unzip ninja
      run:  7z e ninja-win.zip
    - name: setup ndk
      run: echo %ANDROID_NDK% > ndkpath.txt
    - name: miao
      run: cmd /C cd
    - name: miaomiao
      run: dir
    - name: setup system path
      run: cmd /C cd | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: qpm restore
      run: qpm restore
    - name: build
      run: qpm s build
    - name: make qmod
      run: .\scripts\createqmod.ps1
    - name: echo everything
      run: dir
    - uses: actions/upload-artifact@v4
      with:
        name: HeartBeatQuest.qmod
        path: HeartBeatQuest.qmod
        overwrite: true
