name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup qpm
      run: Invoke-WebRequest https://github.com/QuestPackageManager/QPM.CLI/releases/download/v1.3.1/qpm-windows-x64.zip -OutFile qpm-windows-x64.zip 
    - name: unzip qpm
      run:  7z e qpm-windows-x64.zip
  
    - name: echo everything
      run: dir
