name: qmod_build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'UnityUI'
      - 'CHANGELOG'
  pull_request:
    branches: [ "master" ]
  workflow_call:
  
jobs:
  build:
    strategy:
      matrix:
        game-version: [
          # __NEW_VERSION_INSERT_POINT__
          "1.40.8",
          "1.40.7",
          "1.40.6",
          "1.40.4", 
          "1.37.0",
          "1.35.0"
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Apply game version
      run: python multibuild/apply.py ${{ matrix.game-version }}

    - name: QPM Action
      uses: Fernthedev/qpm-action@v1
      with:
        workflow_token: ${{ secrets.GITHUB_TOKEN }}

        restore: true
        cache: true

    - name: build qmod
      run: |
          cd ${GITHUB_WORKSPACE}
          qpm restore
          qpm s build && qpm qmod zip

    - uses: actions/upload-artifact@v4
      with:
        name: qmod.${{ matrix.game-version }}
        path: HeartBeatQuest*.qmod
        overwrite: true