name: qmod_build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
      - 'UnityUI'
      - 'CHANGELOG'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Create ndkpath.txt
      run: |
        echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
        cat ${GITHUB_WORKSPACE}/ndkpath.txt

    - name: Restore vcpkg binary
      uses: actions/cache/restore@v4
      with:
        path: |
          .vcpkg_cache
          vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-
    - name: create cache dir
      if: steps.cache.outputs.cache-hit != 'true'
      run: mkdir .vcpkg_cache
    - name: setup vcpkg
      env: 
        VCPKG_BINARY_SOURCES: "clear;files,//remote/shared/vcpkg/binary-cache,read;files,${{ github.workspace }}/.vcpkg_cache,readwrite"
      run: vcpkg install --triplet arm64-android
    - name: save vcpkg cache
      uses: actions/cache/save@v4
      with:
        path: |
          .vcpkg_cache
          vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        
    - name: QPM Action
      uses: Fernthedev/qpm-action@v1
      with:
        workflow_token: ${{ secrets.GITHUB_TOKEN }}

        restore: true
        cache: true

    - name: build qmod
      run: |
          export VCPKG_ROOT=${VCPKG_INSTALLATION_ROOT}
          cd ${GITHUB_WORKSPACE}
          ls -al
          qpm restore
          pwsh ./scripts/build.ps1 && pwsh ./scripts/createqmod.ps1 -QmodName HeartBeatQuest_1.40.6
          
    - name: echo everything
      run: ls -al
    - uses: actions/upload-artifact@v4
      with:
        name: HeartBeatQuest.qmod
        path: HeartBeatQuest*.qmod
        overwrite: true
