name: qmod_upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Update Dependency
      id: update
      run: python multibuild/auto_update_version.py
    - name: Create Pull Request
      if: steps.update.outputs.updated == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PR_TOKEN }}
        title: "[bot] Add version support for ${{ steps.update.outputs.version }}"
        body: Automated changes by `multibuild/auto_update_version.py`
        branch: auto-bump/${{ steps.update.outputs.version }}
        commit-message: auto bump for ${{ steps.update.outputs.version }}
